### ISSUE TITLE
Mifare Classic 1K: Authentication Error after Multiple Writes

### ISSUE THREAD

**Issue by therealri** [pokusew/nfc-pcsc#16]
Hi @pokusew,

Something weird is happening when attempting multiple writes. I have the following simple script that (1) Authenticates Blocks 4-7, Reads Blocks 4-7 and then Writes to Blocks 4-7.

It seems that the cards become unusable after attempting multiple write operations as they refuse to Authenticate. I have also tried this using promises.

I really like this package due to its quality, straightforward installation across platforms and Electron support.

Any suggestions or advice from your side?

https://gist.github.com/therealri/96adfa625d8bb3b2929a956ec1919cda

```
1:53:04 AM info ACS ACR122 0  device attached
1:53:05 AM info ACS ACR122 0  card detected
card:
  type: TAG_ISO_14443_3
  uid:  4e62e3f5
1:53:05 AM error ACS ACR122 0  error when authenticating data
card:
  type: TAG_ISO_14443_3
  uid:  4e62e3f5
err:
  name: AuthenticationError
  code: operation_failed
```
